### ISSUE TITLE
An error occurs if Wind->deg does not exist

### ISSUE THREAD

**Issue by cookie-maker** [cmfcmf/OpenWeatherMap-PHP-Api#101]
An error occurs if Wind->deg does not exist.
Sometimes you can not get it depending on the city.

[For example]
method : OpenWeatherMap->getWeatherGroup
The city id : 2113126(Akita,Japan）
Wind Object has only 'speed'.

[Error Message]
Undefined property: stdClass::$deg
OpenWeatherMap/CurrentWeather.php
Line Number: 122

**Comment by cmfcmf** [comment]
Hey @cookie-maker,
thanks for the detailed report including examples!
A fix is on it's way! 🍪

**Comment by cmfcmf** [comment]
@cookie-maker this should be fixed as of version 2.2.1.

**Comment by cookie-maker** [comment]
@cmfcmf Thank you!
