### ISSUE TITLE
Simple Forecasting

### ISSUE THREAD

**Issue by jwill89** [cmfcmf/OpenWeatherMap-PHP-Api#107]
Hey All.

Following the examples provided, I was able to get forecast data, but as specified days less than or equal to 5 provide the 5-day 3-hour data. I'm really looking for a simple high/low, icon URL, and cloud description for the two days *after* today (not including today). Is there a way to specify this in the system somewhere or use an alternate to `getWeatherForecast`? Thanks.

**Comment by jwill89** [comment]
Closing the issue. The query seems to fail randomly, but less so when using the `zip:ZIPCODE,US` format as opposed to a `City,STATE` format. Switching to `getDailyWeatherForecast` with the zipcode gave me the information I was looking for.

**Comment by cmfcmf** [comment]
Alright, cool 👍 
I know the current lack of documentation / structure of the examples can sometimes be confusing. If you'd like to help improve it, you're welcome to create a pull request.
