### ISSUE TITLE
Windspeed in Imperial should be mph instead of mps

### ISSUE THREAD

**Issue by haydeniv** [cmfcmf/OpenWeatherMap-PHP-Api#113]
Per: https://openweathermap.org/current

> wind
>     wind.speed Wind speed. Unit Default: meter/sec, Metric: meter/sec, Imperial: **miles/hour**.

**Cmfcmf/OpenWeatherMap/Forecast.php**

This code:
```
        // This is kind of a hack, because the units are missing in the xml document.
        if ($units == 'metric') {
            $windSpeedUnit = 'm/s';
        } else {
            $windSpeedUnit = 'mps';
        }
```

Should be this:
```
        // This is kind of a hack, because the units are missing in the xml document.
        if ($units == 'metric') {
            $windSpeedUnit = 'm/s';
        } else {
            $windSpeedUnit = 'mph';
        }
```

**Comment by cmfcmf** [comment]
Hi @haydeniv,
thanks for letting me know! I fixed the issue in #115. I'll merge it once CI completes and then release a new version.
