### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by contactmayankjain** [cmfcmf/OpenWeatherMap-PHP-Api#114]
composer require "cmfcmf/openweathermap-php-api"
Using version ^2.2 for cmfcmf/openweathermap-php-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package cmfcmf/openweathermap-php-api No version set (parsed as 1.0.0) is satisfiable by cmfcmf/openweathermap-php-api[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by cmfcmf** [comment]
Hi @contactmayankjain,

I'm afraid I can't reproduce the behaviour you described. Please give more context.
```bash
cmfcmf@Christian-PC:/tmp$ composer --version
Composer version 1.6.2 2018-01-05 15:28:41
cmfcmf@Christian-PC:/tmp$ composer require "cmfcmf/openweathermap-php-api"
Using version ^2.2 for cmfcmf/openweathermap-php-api
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing cmfcmf/openweathermap-php-api (v2.2.2): Loading from cache
Writing lock file
Generating autoload files
```
