### ISSUE TITLE
Timezone Specification (#120) might have fixed the 'not-so-forecast' problem

### ISSUE THREAD

**Issue by Clpsplug** [cmfcmf/OpenWeatherMap-PHP-Api#121]
# Summary

We fixed the timezone issue (#119) in #120. I suspect this fix by chance made the 'not-so-forecast' problem fixed by #64 *gone<sup>1</sup>* you describe starting right here as well:

https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/blob/a15fd886dcdba9341a5025dd2c7bb5604c7be163/Cmfcmf/OpenWeatherMap/WeatherForecast.php#L86

... and it may be safe for us to remove this block of code.

<sup>1</sup>in that, the problem don't exist anymore.

# Details

**Before** the fix, in this line we were comparing `$today = new DateTime()`, which was the current time in current timezone and was always correct, with `$date = new \DateTime(isset($time['day']) ? $time['day'] : $time['to'])`, which was the formatted UTC date parsed in current timezone and could be wrong.  

In the environment where our timezone is ahead of UTC (like Asia/Tokyo), that would cause `$date` to fall way behind the intended time (-9 hours if Asia/Tokyo,) which will, when the time difference between UTC and our timezone is big enough, cause `$date < $today`.

When I was poking around #119 (trying different timezones etc.,) this behavior looked really like a timezone related issue because what was being omitted have changed depending on the zones. However, the time zone issue has been fixed in v2.3.0. So I started examining the response XML, and I still haven't found any forecast whose `$date < $today`. I'll keep an eye on those XMLs for a little while (to minimize the fear of the existence of 'not-so-forecasts,') but I think we can safely delete that `if` statement. Let me know if you did experience the 'not-so-forecast' with v2.3.0 :)

**Comment by cmfcmf** [comment]
Hey @Clpsplug, now that it's been two weeks, did you notice any XML "not-so-forecast" responses?

**Comment by cmfcmf** [comment]
Ping @Clpsplug

**Comment by Clpsplug** [comment]
OOPS, sorry @cmfcmf!  
I think we are safe. I did not find XML responses that consist invalid forecast.  
The only case invalid forecasts appear, though, would be when the API took too long to respond to requests done near the '3rd-o' clocks' (is that how we say it? I mean 3:00, 6:00, etc. lol,) but that won't create many problems.

**Comment by cmfcmf** [comment]
> I think we are safe. I did not find XML responses that consist invalid forecast.

Alright, thank you!

**Comment by cmfcmf** [comment]
Fixed by #122.
