### ISSUE TITLE
null temperature,humidity,presure,etc..

### ISSUE THREAD

**Issue by leosalass** [cmfcmf/OpenWeatherMap-PHP-Api#123]
im getting the important data as null:

{"errors":false,"success":true,"status_code":"OK","messages":[],"data":{"city":{"id":3689147,"name":"Barranquilla","country":"CO","population":null,"lat":10.99,"lon":-74.81},"temperature":{"now":{},"min":{},"max":{},"day":null,"morning":null,"evening":null,"night":null},"humidity":{},"pressure":{},"wind":{"speed":{},"direction":{}},"clouds":{},"precipitation":{},"sun":{"rise":{"date":"2018-06-09 10:35:56.000000","timezone_type":3,"timezone":"UTC"},"set":{"date":"2018-06-09 23:21:14.000000","timezone_type":3,"timezone":"UTC"}},"weather":{"id":801,"description":"algo de nubes","icon":"02n"},"lastUpdate":{"date":"2018-06-09 04:00:00.000000","timezone_type":3,"timezone":"UTC"}}}

**Comment by leosalass** [comment]
im using laravel 5.6

**Comment by cmfcmf** [comment]
Hi @leosalass,

could you please also post the code you are using? Thanks! :100:

**Comment by cmfcmf** [comment]
Closing this for now. If you have further problems, please let me know and provide the code you are using. 👍
