### ISSUE TITLE
Not able to load file autoload.php , i have created php environment inside docker

### ISSUE THREAD

**Issue by Rachit77s** [cmfcmf/OpenWeatherMap-PHP-Api#124]
PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/sampleapi.php on line 6
PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/sampleapi.php on line 6

**Comment by cmfcmf** [comment]
Hi @Rachit77s,

Have you resolved your problem yet? If not, please provide more information
about what exactly you are trying to do and what exact steps you took. To
me, it looks like you didn't use Composer (correctly) to install this
library.

>

**Comment by Rachit77s** [comment]
Yes , i got the solution.
Thank you!
