### ISSUE TITLE
UV API not working

### ISSUE THREAD

**Issue by vascosimoes** [cmfcmf/OpenWeatherMap-PHP-Api#127]
When requesting UV data, the response is always 404.

The current method uses the old UVI API [(https://openweathermap.org/api/old-uvi)](https://openweathermap.org/api/old-uvi). It should be changed to the current API methods [(https://openweathermap.org/api/uvi)](https://openweathermap.org/api/uvi).

**Comment by cmfcmf** [comment]
This is now fixed by #132.
