### ISSUE TITLE
GuzzleAdapter and Requestfactory excessive

### ISSUE THREAD

**Issue by KarelWintersky** [cmfcmf/OpenWeatherMap-PHP-API#136]
cmfcmf/openweathermap-php-api: ^3.0

does not work with 'recommended' (really?)
```
         "guzzlehttp/guzzle": "^6.3",
        "graham-campbell/guzzle-factory": "^3.0"
```

I think, custom HTTP Request factory and HTTP client is excessive.

**Comment by cmfcmf** [comment]
Hi @KarelWintersky,

I understand that requiring to install two separate libraries can be excessive if you just want to retrieve some weather data. However, most bigger projects will likely already have PSR-17/18-compatible libraries installed.
The example in the README lists two working libraries and their versions that you could try:
- `http-interop/http-factory-guzzle` `^1.0` 
- `php-http/guzzle6-adapter` `^2.0 || ^1.0`
