### ISSUE TITLE
$owm->getDailyWeatherForecast()

### ISSUE THREAD

**Issue by zkimi** [cmfcmf/OpenWeatherMap-PHP-API#147]
Hello,

I have a problem, the method $owm->getWeatherForecast() works well for me, but I wanted to have only the 3 daily weather forecast so I used $owm->getWeatherForecast() but it throws me an error, could you help me please ?

`Fatal error: Uncaught Cmfcmf\OpenWeatherMap\Exception: OpenWeatherMap returned a response with status code 401 and the following content `{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}` in D:\Xampp2\htdocs\meteo\OpenWeatherMap\vendor\cmfcmf\openweathermap-php-api\Cmfcmf\OpenWeatherMap.php:589 Stack trace: #0 D:\Xampp2\htdocs\meteo\OpenWeatherMap\vendor\cmfcmf\openweathermap-php-api\Cmfcmf\OpenWeatherMap.php(472): Cmfcmf\OpenWeatherMap->cacheOrFetchResult('https://api.ope...') #1 D:\Xampp2\htdocs\meteo\OpenWeatherMap\vendor\cmfcmf\openweathermap-php-api\Cmfcmf\OpenWeatherMap.php(267): Cmfcmf\OpenWeatherMap->getRawDailyForecastData('Berlin', 'metric', 'de', '', 'xml', 2) #2 D:\Xampp2\htdocs\meteo\index.php(26): Cmfcmf\OpenWeatherMap->getDailyWeatherForecast('Berlin', 'metric', 'de', '', 2) #3 {main} thrown in D:\Xampp2\htdocs\meteo\OpenWeatherMap\vendor\cmfcmf\openweathermap-php-api\Cmfcmf\OpenWeatherMap.php on line 589`

PS: I put my API key in OpenWeatherMap.php on line 105.
Thank you!

**Comment by cmfcmf** [comment]
Hi @zkimi,

please provide a reproducible code snippet of how you call the library. Did you follow the [Getting Started](https://cmfcmf.github.io/OpenWeatherMap-PHP-API/docs/getting-started) section?

Note that you should *not* edit the `OpenWeatherMap.php` file but rather set your API key in the constructor parameter as can be seen in the example in the [Usage](https://christianflach.de/OpenWeatherMap-PHP-API/docs/usage) section.

**Comment by zkimi** [comment]
Hi thanks for your answer, yes I followed the Getting Started section.

![Screenshot_1](https://user-images.githubusercontent.com/20417186/81941409-12060080-95f9-11ea-9a80-cefa29819d89.png)

Here's the file I made. 
I put my API key where I wrote "MY API KEY IS HERE" and removed it in OpenWeatherMap.php and error is still here.

Thank you.

**Comment by cmfcmf** [comment]
Thank you for your clarification :+1: 
I'm afraid I can't reproduce the issue, it works for me.
Does calling 

https://api.openweathermap.org/data/2.5/weather?q=Berlin&APPID=XXXXXXXXXXXXXXXXXXXXXXXX

with the X's replaced by your API key produce a result?

**Comment by zkimi** [comment]
Yes I do have a result, that's really weird...
![Screenshot_2](https://user-images.githubusercontent.com/20417186/81942835-e84dd900-95fa-11ea-8b3b-70f2d57bea89.png)

**Comment by cmfcmf** [comment]
Ahh, maybe that's because the daily forecast API is not available for free API keys: https://openweathermap.org/price. You will have to use the `getWeatherForecast` API to retrieve 3-hourly forecasts instead, I suppose.

I didn't notice that initially, because the API key I use for testing does not seem to have this limitation for some reason.

**Comment by zkimi** [comment]
Okay, thanks.

So how do I have the daily forecast for the next 3 days? I have to pay? :(
Thought it was free...
