### ISSUE TITLE
Update code and README to reflect changes on the OpenWeatherMap homepage

### ISSUE THREAD

**Issue by cmfcmf** [cmfcmf/OpenWeatherMap-PHP-Api#17]

**Comment by RossMBoswell330** [comment]
I see this is assigned to yourself. I don't mind doing this if it saves you some time.

**Comment by cmfcmf** [comment]
Thanks, would be great if you could do it!

**Comment by Kickball** [comment]
Any updates on this issue's progress?

**Comment by cmfcmf** [comment]
No sorry. I'd be happy if someone else could do this.
