### ISSUE TITLE
update to psr/cache to 3.0 ?

### ISSUE THREAD

**Issue by B0bbyD0llar** [cmfcmf/OpenWeatherMap-PHP-API#178]
Hi,
is it possible to upgrade psr/cache to version 3?
I have to use symfony/cache ^6.0, but this requires psr/cache ^2.0|^3.0

**Comment by cmfcmf** [comment]
Hey @B0bbyD0llar,
I've looked into it, and supporting `psr/cache` version `^2.0` should be possible as soon as there is a new release of https://github.com/php-cache/cache that supports `^2.0`. They made the necessary changes to support `psr/cache` verison `^2.0` just a couple of days ago, so let's hope there is going to be a new release soon.
