### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by hevilp** [cmfcmf/OpenWeatherMap-PHP-Api#18]
php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package cmfcmf/openweathermap-php-api 1.0.0 could not be found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

{
    "name": "cmfcmf/openweathermap-php-api",
    "description": "A php api to parse weather data from OpenWeatherMap.org. This api tries to normalise and abstract the data and remove inconsistencies.",
    "keywords": ["weather", "OpenWeatherMap", "weather api"],
    "homepage": "https://github.com/cmfcmf/OpenWeatherMap-PHP-Api",
    "license": "MIT",
    "authors": [
        {
            "name": "Christian Flach (cmfcmf)",
            "email": "cmfcmf.flach@gmail.com",
            "homepage": "http://cmfcmf.github.io",
            "role": "Developer"
        }
    ],
    "support": {
        "issues": "https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/issues",
        "source": "https://github.com/cmfcmf/OpenWeatherMap-PHP-Api.git"
    },
    "require": {
        "php": ">=5.3.0",
        "cmfcmf/openweathermap-php-api": "~2.0"
    },
    "autoload": {
        "psr-0": {
            "Cmfcmf\": ""
        }
    }
}

**Comment by cocomo** [comment]
Is there a way to install OpenWeatherMap-PHP-Api without composer? I was able to run the examples in no time by just replacing the existing requires to autoload.php with relative paths. Now i have a hard time getting the classes to work in a legacy systems __autoload() function.

**Comment by cocomo** [comment]
Got it! Just had to enhance the existing autoloader with some handling for namespaces

```
function __autoload ($className) {
    # require_once($className.'.php');
    
    # handle also namespaces
    $className = ltrim($className, '\\');
    $fileName  = '';
    $namespace = '';
    if ($lastNsPos = strripos($className, '\\')) {
        $namespace = substr($className, 0, $lastNsPos);
        $className = substr($className, $lastNsPos + 1);
        $fileName  = str_replace('\\', DIRECTORY_SEPARATOR, $namespace) . DIRECTORY_SEPARATOR;
    }
    $fileName .= str_replace('_', DIRECTORY_SEPARATOR, $className) . '.php';
    // $fileName .= $className . '.php'; //sometimes you need a custom structure
    //require_once "library/class.php"; //or include a class manually
    require $fileName;
}
```

**Comment by cmfcmf** [comment]
Hi @cocomo,
glad to hear you found a way to handle the PSR-0 autoloading. :smiley:

**Comment by pandeytanmay** [comment]
```
{
"require" : {
    "facebook/php-sdk-v4" : "~5.0",
    "twbs/bootstrap": "^3.3",
    "phpclasses/choroscope": ">=1.0.0",
     "cmfcmf/openweathermap-php-api": "~2.0"
     },
  "repositories":
  [
    {
      "type": "composer",
      "url": "http:\/\/www.phpclasses.org\/"
    },
    {
      "packagist": false
    }
  ]
}

```
This is my composer.json file, and I'm getting  errors
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package cmfcmf/openweathermap-php-api could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
`

Please guide me.
