### ISSUE TITLE
"Docusaurus" is spelled wrong in README.md

### ISSUE THREAD

**Issue by mbomb007** [cmfcmf/OpenWeatherMap-PHP-API#183]
> The documentation is built using [Docusuaurs v2](https://v2.docusaurus.io/).

Should be

> The documentation is built using [Docusaurus v2](https://v2.docusaurus.io/).

**Comment by cmfcmf** [comment]
Thanks for noticing this! fixed in https://github.com/cmfcmf/OpenWeatherMap-PHP-API/commit/255b93e2d59d8457e970e1192e3f7f8d46c81ac1.
