### ISSUE TITLE
sunrise and sunset times timezones incorrectly handled

### ISSUE THREAD

**Issue by peterbulmer** [cmfcmf/OpenWeatherMap-PHP-Api#20]
Sunrise and sunset times from owm appear to be ISO8601 formatted times (at least loosely), but they don't specify a timezone (they are UTC).
When datetime objects are created from these timestamps, no timezone is explicitly specified, and php assumes it's my localtime.

**Comment by cmfcmf** [comment]
Fixed by #21.
