### ISSUE TITLE
language code doesn't work

### ISSUE THREAD

**Issue by caBBAlainB** [cmfcmf/OpenWeatherMap-PHP-Api#22]
hello,
I tried to call $weather = $owm->getWeather('Mende, Fr', 'metric', $lang); with $lang = 'fr', 'de', same, i always get the result in English.
Certainly a problem of parameter passed in the url because if I directly access to openWeather, I get translated results.

**Comment by cmfcmf** [comment]
Hi @caBBAlainB,

the lang parameter should be correctly included in the url. Could you please try to add `echo $url;` [here](https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/blob/master/Cmfcmf/OpenWeatherMap.php#L352) and post the url? Thanks.

**Comment by caBBAlainB** [comment]
Yes,
When when ask for a request with city name, units and language are not well passed:

$owm->getWeather($site->city .',' . $site->postcode, ',' . $site->country->code, 'metric', 'fr');

http://api.openweathermap.org/data/2.5/weather?q=Hures+la+Parade%2C48150&units=,fr&lang=metric&mode=xml&APPID=fr'

It's ok when we make the request with coordinates:

$owm->getWeather(['lat' => $site->latitude, 'lon' => $site->longitude], 'metric', 'fr);

http://api.openweathermap.org/data/2.5/weather?lat=44.221078&lon=3.356774&units=metric&lang=fr&mode=xml&APPID=5df9d03c4c6da5e34fa8368385e2778b

Regards,
Alain

**Comment by caBBAlainB** [comment]
Sorry, I reopen it, but again, I wonder if it comes from your side:

My code is the following one:

Line 389    $curWeather = $owm->getWeather($site->city . ',' . $site->postcode . ',' . $site->country->code, 'metric', 'fr');
Line 390    debug($curWeather->clouds->getDescription());
Line 391    $rawWeather = $owm->getRawWeatherData($site->city . ',' . $site->postcode . ',' . $site->country->code, 'metric', 'fr', '', 'json');
Line 392    debug($rawWeather);

And I inserted a debug($url) in your getRawWeatherData() line 352.

result is:

 \vendor\cmfcmf\openweathermap-php-api\Cmfcmf\OpenWeatherMap.php (line 352)

'http://api.openweathermap.org/data/2.5/weather?q=Hures+la+Parade%2C48150%2Cfr&units=metric&lang=fr&mode=xml'

\src\Controller\DeviceconnectionsController.php (line 390)

'clear sky'

\vendor\cmfcmf\openweathermap-php-api\Cmfcmf\OpenWeatherMap.php (line 352)

'http://api.openweathermap.org/data/2.5/weather?q=Hures+la+Parade%2C48150%2Cfr&units=metric&lang=fr&mode=json'

\src\Controller\DeviceconnectionsController.php (line 392)

'{"coord":{"lon":3.43,"lat":44.25},"sys":{"message":0.0184,"country":"France","sunrise":1425881331,"sunset":1425923080},"weather":[{"id":800,"main":"Clear","description":"ensoleillé","icon":"01d"}],"base":"cmc stations","main":{"temp":13.637,"temp_min":13.637,"temp_max":13.637,"pressure":930.1,"sea_level":1038.49,"grnd_level":930.1,"humidity":40},"wind":{"speed":1.06,"deg":355.001},"clouds":{"all":0},"dt":1425901293,"id":0,"name":"Hures-la-Parade","cod":200}
'

As you can see, both urls seem to be correct but the first one returns a not translated result (clear sky and ensoleillé for the second one).

Regards,

**Comment by cmfcmf** [comment]
So the XML version doesn't properly translate the result? This might be another bug with the Api.

**Comment by hubdotcom** [comment]
Yes it appears so

<weather> does have the correct translated info

**Comment by s-reshetnikov** [comment]
hi, it reproduced, again..
my url :
http://api.openweathermap.org/data/2.5/weather?q=MINSK&lang=ru&appid=*********
