### ISSUE TITLE
Incorrect current weather values

### ISSUE THREAD

**Issue by caBBAlainB** [cmfcmf/OpenWeatherMap-PHP-Api#23]
hello,
I remark that the current values you get from the getweather() request are not the current ones but the ones at 06:00.

For example I made a test at 11:53 on a little French town.

$rawWeather = $owm->getRawWeatherData(['lat' => '44.178299', 'lon' => ''3.4298'], 'metric', $language, $OpenWeatherApiKey, 'json');

result from is : (notice temperature of 6.6)

 \src\Controller\DeviceconnectionsController.php (line 395)

[
	'coord' => [
		'lon' => (float) 3.36,
		'lat' => (float) 44.22
	],
	'sys' => [
		'type' => (int) 3,
		'id' => (int) 59713,
		'message' => (float) 0.0484,
		'country' => 'FR',
		'sunrise' => (int) 1425881346,
		'sunset' => (int) 1425923097
	],
	'weather' => [
		(int) 0 => [
			'id' => (int) 800,
			'main' => 'Clear',
			'description' => 'ensoleillÃ©',
			'icon' => '01d'
		]
	],
	'base' => 'cmc stations',
	'main' => [
		'temp' => (float) 6.6,
		'temp_min' => (float) 6.6,
		'temp_max' => (float) 6.6,
		'pressure' => (float) 1038.49,
		'humidity' => (int) 40
	],
	'wind' => [
		'speed' => (float) 1.06,
		'deg' => (float) 355.001
	],
	'clouds' => [
		'all' => (int) 0
	],
	'dt' => (int) 1425896398,
	'id' => (int) 6449384,
	'name' => 'Meyrueis',
	'cod' => (int) 200
]

Remark that you get these values from forecast request:
$rawForecastDatas = $owm->getRawHourlyForecastData(['lat' => '44.178299', 'lon' => '3.4298', 'metric', $language, $OpenWeatherApiKey, 'json');

result is: (notice temperature of 6.6 at 06:00)
[
	(int) 0 => [
		'dt' => (int) 1425891600,
		'main' => [
			'temp' => (float) 6.6,
			'temp_min' => (float) 6.6,
			'temp_max' => (float) 6.6,
			'pressure' => (float) 1038.49,
			'sea_level' => (float) 1038.49,
			'grnd_level' => (float) 1038.49,
			'humidity' => (float) 40,
			'temp_kf' => (float) 0
		],
		'weather' => [
			(int) 0 => [
				'id' => (int) 800,
				'main' => 'Clouds',
				'description' => 'clear sky',
				'icon' => '01d'
			]
		],
		'clouds' => [
			'all' => (float) 0
		],
		'wind' => [
			'speed' => (float) 1.06,
			'deg' => (float) 355.001
		],
		'sys' => [
			'pod' => 'd'
		],
		'dt_txt' => '2015-3-9 09:00:00'
	],
	(int) 1 => [
		'dt' => (int) 1425913200,
		'main' => [
			'temp' => (float) 19.82,
			'temp_min' => (float) 14.97,
			'temp_max' => (float) 19.82,
			'pressure' => (float) 929.16,
			'sea_level' => (float) 1036.88,
			'grnd_level' => (float) 929.16,
			'humidity' => (int) 34,
			'temp_kf' => (float) 4.86
		],
		'weather' => [
			(int) 0 => [
				'id' => (int) 800,
				'main' => 'Clear',
				'description' => 'ensoleillÃ©',
				'icon' => '01d'
			]
		],
		'clouds' => [
			'all' => (int) 0
		],
		'wind' => [
			'speed' => (float) 1.76,
			'deg' => (float) 5.00757
		],
		'sys' => [
			'pod' => 'd'
		],
		'dt_txt' => '2015-03-09 15:00:00'
	],

But from openWeatherMap website, the current temperature was:
![xeuxmkx](https://cloud.githubusercontent.com/assets/9322571/6553684/99dd79b4-c653-11e4-8172-5c30aee63353.png)

and if I made a request directly:

http://api.openweathermap.org/data/2.5/weather?q=Meyrueis,fr
returned values are:
{"coord":{"lon":3.43,"lat":44.18},"sys":{"message":0.0486,"country":"France","sunrise":1425881328,"sunset":1425923081},"weather":[{"id":800,"main":"Clear","description":"Sky is Clear","icon":"01d"}],"base":"cmc stations","main":{"temp":286.787,"temp_min":286.787,"temp_max":286.787,"pressure":930.1,"sea_level":1038.49,"grnd_level":930.1,"humidity":40},"wind":{"speed":1.06,"deg":355.001},"clouds":{"all":0},"dt":1425898863,"id":6449384,"name":"Meyrueis","cod":200}

We see here that temp=286.787 - 273.15 = 13.6°C 

So it seems there is something wrong in you api.

Hope this help.
regards,

**Comment by cmfcmf** [comment]
I can't reproduce that behaviour. My code looks like so:
```php
$owm = new OpenWeatherMap();

$weather = $owm->getRawWeatherData(['lat' => '44.178299', 'lon' => '3.4298'], 'metric', 'fr', null, 'json');
echo $json;
```
which returns:
```json
{"coord":{"lon":3.43,"lat":44.18},"sys":{"message":0.0971,"country":"FR","sunrise":1425881328,"sunset":1425923081},"weather":[{"id":800,"main":"Clear","description":"ensoleillé","icon":"01d"}],"base":"cmc stations","main":{"temp":13.637,"temp_min":13.637,"temp_max":13.637,"pressure":930.1,"sea_level":1038.49,"grnd_level":930.1,"humidity":40},"wind":{"speed":1.06,"deg":355.001},"clouds":{"all":0},"dt":1425899225,"id":6449384,"name":"Meyrueis","cod":200} 
```
"temp":13.637

**Comment by cmfcmf** [comment]
Does it work if you don't use your api key?

**Comment by caBBAlainB** [comment]
Sorry,
It does not come from you but from openWeather!
You can verify it doing the next 2 requests:

good values with:
http://api.openweathermap.org/data/2.5/weather?q=Meyrueis,fr&mode=xml

bad values with:
http://api.openweathermap.org/data/2.5/weather?lat=44.221078&lon=3.356774&mode=xml

As you can see, it concerns the same city/id. but the reurned values are differents.

**Comment by cmfcmf** [comment]
Okay, you could [contact OpenWeatherMap](https://openweathermap.desk.com/customer/portal/emails/new) and report that problem.

**Comment by caBBAlainB** [comment]
That's done.
Sorry and thanks anyway.
Regards,
