### ISSUE TITLE
Unknown Fatal Error

### ISSUE THREAD

**Issue by caBBAlainB** [cmfcmf/OpenWeatherMap-PHP-Api#24]
Hi,
I very often get a OWMExceptionexception 'Cmfcmf\OpenWeatherMap\Exception' with message 'Unknown fatal error: OpenWeatherMap returned the following json object: ' in C:\...\openweathermap-php-api\Cmfcmf\OpenWeatherMap.php:168

When I call $owm->getRawHourlyForecastData(), immediately followed by $owm->getWeather().
The order of calls doesn't matter. I think that something goes wrong when the owm calls are too close.

I tried to insert a sleep(2) between the 2 calls without success... I wondered if openWeather() could limit the time between 2 requests but as it's 3000 req/min in free account. I don't think that the problem could be here.

Any idea?

**Comment by cmfcmf** [comment]
No, sorry, I don't know what't happening there :disappointed:

**Comment by RossMBoswell330** [comment]
I can't seem to replicate this error. I am calling $owm->getRawHourlyForecastData() followed by $owm->getWeather() but I still don't get the exception. Have you got some example code we could look at? Or are there more specifics to generating this problem?
