### ISSUE TITLE
Typo in php-unit version requirement 

### ISSUE THREAD

**Issue by welly** [cmfcmf/OpenWeatherMap-PHP-Api#32]
Hello,

It seems the php-unit version number is a little incorrect. The ^ operator requires a full version - ^4.7.0 for example, rather than the configured ^4.7 version, which is actually failing when I try to build a project. Any chance you could update this?

Thanks!

**Comment by welly** [comment]
I've created a merge request to update this.

**Comment by cmfcmf** [comment]
Fixed by #33.
