### ISSUE TITLE
@note & Symfony2

### ISSUE THREAD

**Issue by Gerfaut** [cmfcmf/OpenWeatherMap-PHP-Api#34]
Hi and thanks a lot for this great work ! 
I noticed a weird bug when using with Symfony2. 

When I do something like hereunder (in a controller), 

```PHP
// Language of data (try your own language here!):
        $lang = $request->getLocale();

        // Units (can be 'metric' or 'imperial' [default]):
        $units = 'metric';


        $owm = new OpenWeatherMap();

        try {
            $weather = $owm->getWeather($city, $units, $lang);
        } catch(OWMException $e) {
            echo 'OpenWeatherMap exception: ' . $e->getMessage() . ' (Code ' . $e->getCode() . ').';
            echo "<br />\n";
        } catch(\Exception $e) {
            echo 'General exception: ' . $e->getMessage() . ' (Code ' . $e->getCode() . ').';
            echo "<br />\n";
        }

        return $weather;
```

I got this error : 
```PHP
[Semantical Error] The annotation "@note" in method Cmfcmf\\OpenWeatherMap\\Util\\Unit::getFormatted() was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

It seems that the @note annotations are interpreted as standard Symfony annotations... 
If I remove the @note, everything work as expected ! 

Thanks a lot ! 

_Gerfaut_

**Comment by cmfcmf** [comment]
Hi @Gerfaut,

I searched for all [not ignored annotations](https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/AnnotationReader.php#L55) and removed them. Please try if it works now. If you don't have issues anymore, I will release a new version.

**Comment by Gerfaut** [comment]
Hi @cmfcmf, 
Thanks for your fastness !
It is now perfectly working with your update ! 

Do you know if @note and @notice are regular PHP Doc annotations ? Maybe it is more a Doctrine bug ? 
What do you think ? 

Thanks a lot ! 

_Gerfaut_

**Comment by cmfcmf** [comment]
> Thanks for your fastness !
It is now perfectly working with your update ! 

Great!
> Do you know if @note and @notice are regular PHP Doc annotations ? Maybe it is more a Doctrine bug? 

It is a common problem when you or one of your libraries use DoctrineAnnotations to parse PHP files for annotations. It ignores some of the most used annotations (i.e. `@param`), but `@notice` apparently isn't one of them. I wouldn't consider it a bug.
I'm releasing a new version now.
