### ISSUE TITLE
printing temperature in metric gives "17.78 metric" instead of "17.78 °C"

### ISSUE THREAD

**Issue by iamgoodbytes** [cmfcmf/OpenWeatherMap-PHP-Api#35]
Woud it be possible to change "metric" to "°C" when printing temperatures in metric unites? Nobody says "metric".

**Comment by cmfcmf** [comment]
This should already be the case and therefore is a bug. Thanks for reporting!

**Comment by cmfcmf** [comment]
Turns out the API changed and now returns "metric" as temperature unit.

http://api.openweathermap.org/data/2.5/weather?q=London&mode=xml&units=metric

**Comment by iamgoodbytes** [comment]
Oh I see, thanks for the quick response. Maybe it could be set through code e.g. in the getFormatted() function?

**Comment by iamgoodbytes** [comment]
Confirmed working, thanks for the fix. Please let me know when you release an update!

![screen shot 2015-07-14 at 11 55 11](https://cloud.githubusercontent.com/assets/3899360/8670677/429dd880-2a1f-11e5-9321-e9d38f8b094f.png)

**Comment by cmfcmf** [comment]
Released version 2.0.8.

**Comment by iamgoodbytes** [comment]
Fantastic. Works like a charm!
