### ISSUE TITLE
convert hPa to mmHg

### ISSUE THREAD

**Issue by DickLofenak** [cmfcmf/OpenWeatherMap-PHP-Api#40]
Good day. How can i change hPa to mmHg?
I know that this must be like a $pressure = $pressure * 0.75006375541921;
but I can not find where this variable is set to count it.

**Comment by cmfcmf** [comment]
Hi @DickLofenak,

you cannot change the unit directly inside the API. Maybe the following code helps you:
```php
echo ($pressure->getValue() * 0.75006375541921) . 'mmHg';
```
