### ISSUE TITLE
Error: Not found city

### ISSUE THREAD

**Issue by iamgoodbytes** [cmfcmf/OpenWeatherMap-PHP-Api#41]
I'm getting this error more often than not today. Any idea what can be wrong? Something this works, other times it doesn't. This error didn't happen before.

Exception in OpenWeatherMap.php line 165:
Error: Not found city
in OpenWeatherMap.php line 165
at OpenWeatherMap->getWeather(array('lat' => '51.2194475', 'lon' => '4.4024643'), 'metric', 'en', 'myapikeyishere') in Inspection.php line 35

**Comment by cmfcmf** [comment]
Sorry @iamgoodbytes, I don't know why this error pops up that often. You could try contacting the OpenWeatherMap support about the issue. The PHP API, as you see, doesn't do anything special which could cause this error. I don't think I can help here.

**Comment by iamgoodbytes** [comment]
Thanks @cmfcmf - it's probably the API like you said. I was having trouble catching that error when it happens, but I'll figure that one out. Thanks for the reply!
