### ISSUE TITLE
I got API by register but not work error: Invalid API key

### ISSUE THREAD

**Issue by altaihero** [cmfcmf/OpenWeatherMap-PHP-Api#46]
I got api by free register and i added my api to $weather = $owm->getWeather('Berlin', $units, $lang, 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'); xxxxxxx is my api but i got error

OpenWeatherMap exception: Unknown fatal error: OpenWeatherMap returned the following json object: Invalid API key. Please see http://openweathermap.org/faq#error401 for more info. (Code 0).

**Comment by cmfcmf** [comment]
Hi @altaihero, does calling the following URL in your browser work for you (replace the X's by your api key)?

http://api.openweathermap.org/data/2.5/weather?q=Berlin&APPID=XXXXXXXXXXXXXXXXXXXXXXXX

**Comment by altaihero** [comment]
Hi @cmfcmf  i was't use xxxx in APPID xxxx is just example.
But I is fine working today.

**Comment by cmfcmf** [comment]
Ok cool!

**Comment by marlonlom** [comment]
at now, it continue just like that...
`{
cod: 401,
message: "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."
}`

**Comment by cmfcmf** [comment]
Hi @marlonlom!

Does the problem persist? Does calling `
http://api.openweathermap.org/data/2.5/weather?q=Berlin&APPID=XXXXXXXXXXXXXXXXXXXXXXXX` directly from your browser work?
Please note that it takes a few minutes until your new api key is activated.

Let me know if it works now!

**Comment by georgeharnwell** [comment]
Hi @cmfcmf,

I am now having this issue. I can successfully navigate to http://api.openweathermap.org/data/2.5/weather?q=Manchester,UK with my API key. But any of the historical calls I make are returning an Unauthorised error

Kind regards,
George

**Comment by cmfcmf** [comment]
Hi @georgeharnwell, are you on a free account? The historical weather condition api is not free, see http://openweathermap.org/price (it was free a months (years?) ago but isn't anymore).

**Comment by huynhit92** [comment]
Hi @munkh-altai You should use appid not APPID

**Comment by munkh-altai** [comment]
thank you all. My problem solved. ;-)
@huynhit92

**Comment by ibrahimmohammed1** [comment]
i'm calling it with appid={key} and it doesn't work ! this must be some kind of bug and failure in the API

**Comment by cmfcmf** [comment]
> Please note that it takes a few minutes until your new api key is activated.

If the key doesn't work after a few minutes, try contacting the OpenWeatherMap team. I can't really help with that. 😕

**Comment by mcsanantonio** [comment]
I tried the answers above but to no avail. 👎

**Comment by NahidRM** [comment]
Yup, me too. The suggestions here haven't worked

**Comment by xgqfrms-GitHub** [comment]
https://openweathermap.desk.com/customer/portal/questions/14413219-invalid-api-key
http://api.openweathermap.org/data/2.5/weather?q=London&appid==ff474db96b8a859106ef452513a234b9

**Comment by xgqfrms-GitHub** [comment]
https://openweathermap.desk.com/customer/portal/questions/14413219-invalid-api-key

**shit api!**

https://openweathermap.org/faq

https://openweathermap.org/appid

https://github.com/google/maps-for-work-samples/blob/master/samples/maps/OpenWeatherMapLayer/index.html

https://github.com/search?q=openweathermap&ref=cmdform

**Comment by xgqfrms-GitHub** [comment]
https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/issues/46

**Comment by xgqfrms-GitHub** [comment]
https://github.com/liu044100/SmileWeather
https://github.com/buche/leaflet-openweathermap
https://github.com/michael-lynch/open-weather

**Comment by xgqfrms-GitHub** [comment]
## https error

https://api.openweathermap.org/data/2.5/weather?q=London&appid=xxxxxxx

## http ok

http://api.openweathermap.org/data/2.5/weather?q=London&appid=xxxxxxx

**Comment by cmfcmf** [comment]
Hey @xgqfrms-GitHub,

please stop spamming random links and sentences. If this was StackOverflow, I'd close this with "unsure what you are asking"... 

If you are unhappy with what OpenWeatherMap provides, either argue with them directly or use a different, probably paid, service.

**Comment by uri** [comment]
I'm getting this issue too. If I paste the URL in the browser it works fine, but it stop working in my script. Here is the response I get (in Elixir)

```elixir
%HTTPoison.Response{body: "{\"cod\":401, \"message\": \"Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.\"}",
  headers: [{"Server", "openresty"}, {"Date", "Fri, 03 Mar 2017 04:25:04 GMT"},
   {"Content-Type", "application/json; charset=utf-8"},
   {"Content-Length", "107"}, {"Connection", "keep-alive"},
   {"X-Cache-Key", "/data/2.5/weather?q=new%20york%20ny"},
   {"Access-Control-Allow-Origin", "*"},
   {"Access-Control-Allow-Credentials", "true"},
   {"Access-Control-Allow-Methods", "GET, POST"}], status_code: 401}}
```

The URL I'm accessing is `http://api.openweathermap.org/data/2.5/weather?q=New%20York%20NY&appid=<my api key here>`

**Comment by 302wanger** [comment]
If you are a new start,it need ten minutes or more time before the key can use

**Comment by Naveed-anwar123** [comment]
http://samples.openweathermap.org/data/2.5/weather?q=Lahore,PK&appid=542ffd081e67f4512b705f89d2a611b2
Always return London weather. What the heck any body knows?

**Comment by cmfcmf** [comment]
@Naveed-anwar123 you are using the `samples.openweathermap.org` endpoint. You should use the `api.openweathermap.org` endpoint instead.

**Comment by khjoony** [comment]
Caution : Notice the difference between opostrophe and grave key
API - OpenWeatherMap 날씨 Invalid api key

출처: http://booolean.tistory.com/755 [boolean]

**Comment by cmfcmf** [comment]
> Hi im haveing the next error:

Could you please post the code you are using?

**Comment by leosalass** [comment]
It is now working thanks, i made some changes in the code

**Comment by kevinmholbrook** [comment]
what changes did you make?

**Comment by AnneRajan** [comment]
{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}

I am using valid api key still its not working please help

**Comment by YoganandamD** [comment]
If you just signed up, the automated email says that key will be activated in couple of hours. You should check back after couple of hours

**Comment by leosalass** [comment]
> what changes did you make?

sorry, this is too old, i dont remember

**Comment by curenosm** [comment]
Maybe it's just that you have to wait around 30 minutes to start using a new APPID, that happened to me.

**Comment by Arunprasadh93** [comment]
just wait for sometime(15 mins approx) after you signup or generate a api key,  before calling the api 👍

**Comment by aero77** [comment]
same here, invalid key!

**Comment by hirenbhal** [comment]
Remove https:// and just use `api.openweathermap.org/data/2.5/weather?q=alwar&appid=ba24c6018ddd72041749018d0c1b1ef8&units=metric`

**Comment by echu18** [comment]
> Hi @munkh-altai You should use appid not APPID

this worked for me! thanks! I changed APPID to appid in Postman and the weather data replaced the error message

**Comment by aathil-Mr-ITGuy** [comment]
The major problem is, it takes couple of hours to activate the API

**Comment by jmgawecki** [comment]
hey guys. As mentioned before, I cannot get a request through my terminal as it says Invalid API key. But it does work through my browser. 

curl -v http://api.openweathermap.org/data/2.5/weather?q=Berlin&APPID=MYAPIKEY - This is how I do it through my terminal. Is that wrong? Many thanks for help.

**Comment by Minsoo-web** [comment]
Hey guys.
I try to every this of answers and my result was same -> 401 Invalid API Keys

My solution is
```
If you just sign up user or create API keys, just wait a for minutes(or more) it was solved.
```

**Comment by giocorvo** [comment]
> Hi @altaihero, does calling the following URL in your browser work for you (replace the X's by your api key)?
> 
> http://api.openweathermap.org/data/2.5/weather?q=Berlin&APPID=XXXXXXXXXXXXXXXXXXXXXXXX
> 
> **For everyone reading this in the future**: It is most likely that a new API key takes a few minutes until it works.

Hi! For me your link works, (I know the 15-30 minutes of waiting from the creation). Please help me... If it could be useful, the script is here: https://github.com/DelManari/AR-Weather

**Comment by DilinaHirantha** [comment]
you need to wait just 10-15 minutes because it will take  time to activate your API key. after that you can use it as follow,

https://api.openweathermap.org/data/2.5/weather?q=London&appid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

for me it worked perfectly!

**Comment by giocorvo** [comment]
I know the 15-30 minutes of waiting from the creation

**Comment by Andrii-Horpynchenko** [comment]
This is a working template - https://api.openweathermap.org/data/2.5/weather?q=Kharkiv&units=metric&APPID=XXXXXXXXXXXXXXXXXXXXXXXX.
Replace XXXXXXXXXXXXXXXXXXXXXXX with your API key

**Comment by ispysoftware** [comment]
hmm been waiting 2 hours, still getting the same error

**Comment by uzzalcontact** [comment]
https://api.openweathermap.org/data/2.5/forecast/daily?q=dhaka&cnt=16&appid=d43795792c1050d9f397f55993a485d6

{
"cod": 401,
"message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."
}

how i can solve the issues.

**Comment by shubhankar-mern** [comment]
{cod: 401, message: 'Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.'}
my api key is very old....still getting the issue ..why?

**Comment by Jatin9098** [comment]
While working with flutter I have the same issue.
While hitting the URL from browser the URL : https://api.openweathermap.org/data/2.5/weather?lat=26.5778&lon=78.494953&appid=525xxxxxxx598b

and hitting from the mobile URL will be **changed** to 
https://api.openweathermap.org/data/2.5/weather  %**3F**  lat=26.5778&lon=78.494953&appid=525xxxxxxx598b

So after **/data/2.5/weather** use the **query** parameter while hitting the API

for Flutter it is solved below:
 final queryParameters = {
     'lat': '26.5778',
     'lon': 78.494953',
     'appid': '525xxxxxxx598b',
   };
   var url = Uri.https('api.openweathermap.org', '/data/2.5/weather',queryParameters);

**Comment by IoIxD** [comment]
Unfortunately whoever downvoted that person who said it can take two hours was downvoting in vain. 

[OpenWeatherMap themselves say that it can take a few hours for an API key to be valid](https://openweathermap.org/faq#error401). 

Why it takes so long is beyond me but I hope this helps somebody.

**Comment by rajhlinux** [comment]
Had the same issue, took about 20 mins before the API key started to work.

**Comment by SadakVali** [comment]
I too had the same issue, took about 10 mins before the API key started to work.

**Comment by bluecomet1994** [comment]
I'm getting the same response when I try to call this API with specific params.
https://api.openweathermap.org/data/2.5/onecall?lat=xxxx&lon=xxxx&appid=xxxxxx

Is anyone experienced in calling this APIs?
