### ISSUE TITLE
Add new UV api

### ISSUE THREAD

**Issue by cmfcmf** [cmfcmf/OpenWeatherMap-PHP-Api#48]
http://openweathermap.org/api_uv

**Comment by RauchF** [comment]
Hi, are you already working on this? Otherwise I'd be glad to do it and send in a pull request.

**Comment by cmfcmf** [comment]
Hi Felix, I have not started working on it and probably won't for the next
weeks. I'd be more than happy to receive a pull request though!

Felix Rauch <notifications@github.com> schrieb am Mi., 18. Nov. 2015 um
10:31 Uhr:

**Comment by peter279k** [comment]
UV api is still a beta feature now.
The example call in http://openweathermap.org/api_uv is not available. I also get the 502 bad gateway.

And I also found another url: http://openweathermap.org/api/uvi.
It seems the new version of uv api now.

**Comment by peter279k** [comment]
I implement this API feature now.
Please check [this](https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/pull/97).

Thanks.
