### ISSUE TITLE
Feature Request - HTML View

### ISSUE THREAD

**Issue by lee-mustard** [cmfcmf/OpenWeatherMap-PHP-Api#49]
Hey Man, Any tips on how to get the html view working , I dug abit deeper into your library (dont really want to edit the core files.

Lee

**Comment by cmfcmf** [comment]
Hi @lee-mustard,

the HTML view isn't that sophisticated. It returns a full HTML document you could embed via an iframe. This is an example output: https://gist.github.com/cmfcmf/7ddcac18e0aeaea737e8.

Let me know if this helps!

**Comment by lee-mustard** [comment]
Perfect! thanks alot. You got any idea on how to call the current Weather code?
I need to use this to display a suitable icon depending on weather for the day.

ie: sunny icon for a hot day etc etc

http://bugs.openweathermap.org/projects/api/wiki/Weather_Condition_Codes

Once again, Thanks for the direction thus far

**Comment by cmfcmf** [comment]
```php
$owm = new OpenWeatherMap();
$weatherData = $owm->getWeather('Berlin', 'metric', 'en', 'YOUR-APP-ID');
echo $weatherData->weather->getIconUrl():
```
This should echo the url to the correct wheather icon. Let me know if it works.

**Comment by lee-mustard** [comment]
many thanks!
