### ISSUE TITLE
Fatal error</b>:  Uncaught exception 'Cmfcmf\OpenWeatherMap\Exception' with message 'Unknown fatal  error: OpenWeatherMap returned the following json object: ' Line 173

### ISSUE THREAD

**Issue by ferbj** [cmfcmf/OpenWeatherMap-PHP-Api#51]
Hi,  when i want request a response of plugin i get this message sometimes, not always
 error: OpenWeatherMap returned the following json object: ' in D:\xampp\htdocs\sfinal\plugins\Cmfcmf
\vendor\cmfcmf\openweathermap-php-api\Cmfcmf\OpenWeatherMap.php:173

what is the reason about that? .. thanks for your answer...

**Comment by cmfcmf** [comment]
Hi, this means that the Open Weather Map API didn't return valid data. This library therefore couldn't decode it as XML nor as JSON. You could try to debug what the answer contains here before json_decoding it. https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/blob/master/Cmfcmf/OpenWeatherMap.php#L169-L173
