### ISSUE TITLE
Forecast Wind direction parsing issue

### ISSUE THREAD

**Issue by klorie** [cmfcmf/OpenWeatherMap-PHP-Api#52]
Current code uses 'value' xml option field for getting wind direction whereas the xml contains the field 'deg' (which is in fact different from the current weather response...)

Fix is simply to change 'value' to 'deg' in OpenWeatherMap/Forecast.php line 70

Thanks for your library

**Comment by cmfcmf** [comment]
Thank you for reporting this issue @klorie! It should now be fixed. I relased version 2.0.11.
