### ISSUE TITLE
Order weather forecast by timestamp

### ISSUE THREAD

**Issue by moledet** [cmfcmf/OpenWeatherMap-PHP-Api#55]
On some cities when try to get data on 16 day returned 10 days of forecast and after this 6-2 weather data of past days. When go by foreach on data graph is broken. This is bug of API, but can you order data by timestamp when parsing it?

**Comment by cmfcmf** [comment]
Hi @moledet, thank you for your bug report! I could reproduce a similar pattern locally. #64 should fix this.
