### ISSUE TITLE
Daily forecast temperature is calculated incorretly

### ISSUE THREAD

**Issue by aseriy** [cmfcmf/OpenWeatherMap-PHP-Api#66]
When a Forecast object is constructed, it calculates the value for the Temperature->now as the average of the minimum and maximum from the temperature values in the XML message. However, because all values are strings but no conversion to floats is done, the temp values are cast to integers and the resulting average is incorrect.

**Comment by aseriy** [comment]
Fixed the issue and created a pull request.

**Comment by cmfcmf** [comment]
Fixed in #67 / #71.
