### ISSUE TITLE
Why example code is wrong (not up-to-date)?

### ISSUE THREAD

**Issue by intarstudents** [cmfcmf/OpenWeatherMap-PHP-Api#69]
![2016041127f49c](https://cloud.githubusercontent.com/assets/227198/14426368/2c1b6132-fff7-11e5-9b7b-8708e1adc1bf.png)

In other there is `->setApiKey` that doesn't exist also https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/blob/master/Examples/CurrentWeather.php#L41

**Comment by cmfcmf** [comment]
Hi @intarstudents,

the example code actually is up to date. It refers to the current master version. You are probably (as you should!) using the latest released version which worked slightly different. Please refer to the README of version 2.0.x: https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/tree/v2.0.11

I am going to release version 2.1 soon. It will be fully backwards compatible to version 2.0.11.

**Comment by intarstudents** [comment]
Ooo right. roger that.

**Comment by cmfcmf** [comment]
I have now released version 2.1.0 which means you can now follow the master README and pass the API key as first parameter. :smile: 
Sorry for the inconvenience though :confused:
