### ISSUE TITLE
Fatal error on fetch()

### ISSUE THREAD

**Issue by KyleGoslan** [cmfcmf/OpenWeatherMap-PHP-Api#70]
Is there any easy fix to this?

Fatal error: Call to a member function fetch() on string in /Users/kyle/Sites/koma/vendor/cmfcmf/openweathermap-php-api/Cmfcmf/OpenWeatherMap.php on line 551

**Comment by cmfcmf** [comment]
Hi @KyleGoslan,

could you please give more details? Which version / tag do you use? How does your code look like?

**Comment by cmfcmf** [comment]
Oh wait, I see. You are probably having the same issue as described here: https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/issues/69

**Comment by KyleGoslan** [comment]
Yeah, thats the one! Was following the master readme and convinced I was going mental. Just went through the class and worked it out.

Might be useful to note that somewhere obvious :)

**Comment by cmfcmf** [comment]
I have now released version 2.1.0 which means you can now follow the master README and pass the API key as first parameter. :smile: 
Sorry for the inconvenience though :confused:

**Comment by KyleGoslan** [comment]
Not at all, great looking api, appreciate the work!  :)
