### ISSUE TITLE
$lang parameter broken

### ISSUE THREAD

**Issue by Efratror** [cmfcmf/OpenWeatherMap-PHP-Api#86]
I have copied your CurrentWeather example directly to my web-server so i could see how the api works. In the beginning you set the parameter to `de` which should be German but at example 7 the output for wind direction and wind speed description are in English.

**Comment by cmfcmf** [comment]
Hey @Efratror, 
this is something I cannot fix. See the following API call for reference:
http://api.openweathermap.org/data/2.5/weather?q=London,uk&appid=2f8796eefe67558dc205b09dd336d022&lang=de&mode=xml

You could try asking for help here: https://openweathermap.desk.com/.
