### ISSUE TITLE
I am missing an example with icon usage

### ISSUE THREAD

**Issue by chriszo111** [cmfcmf/OpenWeatherMap-PHP-Api#89]
The weather icon ID is available, but as for now I did not find any examples that are using icons. However, this lead me to having problems finding out how to use the icons that are called. I could dig a lot deeper to find out, but wouldn't it be better to have an example at [Examples/CurrentWeather.php](https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/blob/master/Examples/CurrentWeather.php)?

**Comment by cmfcmf** [comment]
Hello @chriszo111,
I've now added a new example to show how to retrieve the icon id and also how to retrieve the url to an actual icon. Hope it helps!
```php
$weather = $owm->getWeather('Berlin');
echo $weather->weather->icon;
echo $weather->weather->getIconUrl();
```

**Comment by chriszo111** [comment]
Perfectly fine, except for one question looking at the method retrieving the icon:
I have to use `$weather->weather[0]->icon` because like in the documentation of the JSON API it responds with `"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],` - hence `weather` is wrapped within an array?

**Comment by cmfcmf** [comment]
I'm afraid I can'r really reproduce what you said. Can you share the full code sample @chriszo111? Thanks!
