### ISSUE TITLE
New url for historical datas

### ISSUE THREAD

**Issue by gmesnard** [cmfcmf/OpenWeatherMap-PHP-Api#90]
Hello,

The url to access Historical Datas from OWM API is broken in Cmfcmf/OpenWeatherMap.php (line 68).
`private $weatherHistoryUrl = 'http://api.openweathermap.org/data/2.5/history/city?';`

You should use the new url : 
`private $weatherHistoryUrl = 'http://history.openweathermap.org/data/2.5/history/city?';
`

Regards

**Comment by cmfcmf** [comment]
Thanks! Has been fixed now.
