### ISSUE TITLE
error temp max y min

### ISSUE THREAD

**Issue by virla01** [cmfcmf/OpenWeatherMap-PHP-Api#91]
I get an error when setting the max and min temperature together with the temperature gives me the same value.
$miclima = array(
	'temp' => $weather->temperature->now,
	'tmin' => $weather->temperature->min,
	'tmax' => $weather->temperature->max,
	'hum' => $weather->humidity,
	'vel' => $weather->wind->speed,
	'dir' => $weather->wind->direction
);

**Comment by cmfcmf** [comment]
Sorry @virla01, I am unsure what exactly you're asking 😕

**Comment by virla01** [comment]
The maximum and minimum temperature gives me the same value, and should give two different values

**Comment by cmfcmf** [comment]
> The maximum and minimum temperature and the temperature, give me the same value, and must be different values.
> http://aspectox.esy.es/img/temp.png

This does appear to be an issue with the API, not this PHP library. Please contact OpenWeatherMap if you have further questions, I can't help with theses issues.
