### ISSUE TITLE
remove http: from Icon URL

### ISSUE THREAD

**Issue by getriebesand** [cmfcmf/OpenWeatherMap-PHP-Api#92]
please remove http: from URL for use in https sites.

and make $iconUrl protected so it can be modified to customer needs (own icons)

protected $iconUrl = "//openweathermap.org/img/w/%s.png";

**Comment by cmfcmf** [comment]
Hey @getriebesand,
I've now removed `http:` from the icon urls and updated the weather class to include a setter to change the icon url template globally:
```php
\Cmfcmf\OpenWeatherMap\Util\Weather::setIconUrlTemplate('//myicons.mysite.com/icon/%s');
/* ... */
$owm = new \Cmfcmf\OpenWeatherMap('...');
/* ... */
```
